#!/usr/bin/env python3
"""Python port of generate_skill_index.ps1 (T1585).

Generates SKILL_INDEX.md across all 5 IDE skill folders from canonical
.cursor/skills/g-skl-*/SKILL.md frontmatter (Task 873, Skill Chaining).

The SKILL_INDEX.md file is a one-line-per-skill catalogue that lets agents
discover skills without loading their full bodies. The script:
  1. Walks .cursor/skills/g-skl-* for SKILL.md files
  2. Parses frontmatter `name:` and `description:` (plain and folded `>-` forms)
  3. Emits SKILL_INDEX.md to .cursor/, .claude/, .agent/, .codex/, .opencode/
     skill folders
  4. Is idempotent - re-running on unchanged input yields unchanged output

.copilot/ has commands only (no skills folder) and is excluded by design.
"""
# @subsystems: PROJECT_IDENTITY_SETUP
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path
from typing import List, Optional, Tuple


# UTF-8-safe stdio on Windows consoles (the PS1 originals emit Unicode glyphs)
for _stream in (sys.stdout, sys.stderr):
    if hasattr(_stream, "reconfigure"):
        _stream.reconfigure(encoding="utf-8", errors="replace")


def _bootstrap_engine() -> bool:
    """Make ``gald3r.utils`` importable; fall back to the bundled engine source."""
    try:
        import gald3r.utils  # noqa: F401
        return True
    except ImportError:
        pass
    here = Path(__file__).resolve()
    for parent in here.parents:
        engine_src = parent / ".gald3r_sys" / "engine" / "src"
        if engine_src.is_dir():
            sys.path.insert(0, str(engine_src))
            try:
                import gald3r.utils  # noqa: F401
                return True
            except ImportError:
                return False
    return False


_HAS_ENGINE = _bootstrap_engine()

TARGET_DIRS = (".cursor/skills", ".claude/skills", ".agent/skills",
               ".codex/skills", ".opencode/skills")

HEADER_LINES = (
    "# Skill Index -- gald3r-managed skills",
    "",
    "> Auto-generated by `.claude/skills/g-skl-setup/scripts/"
    "generate_skill_index.py`. Do not hand-edit.",
    "> Regenerate after adding/removing/renaming any `g-skl-*` skill.",
    "> Source of truth: `.cursor/skills/g-skl-*/SKILL.md` frontmatter "
    "(`name:` + `description:`).",
    "",
    "This index lets agents discover skills without loading the full "
    "SKILL.md body.",
    "See `docs/20260507_*_Cursor_SKILL_CHAINING_ARCHITECTURE.md` for the "
    "reference-mode",
    "loading contract and the `## Summary` block convention on each "
    "individual skill.",
    "",
    "## Index",
    "",
)


def get_skill_frontmatter(path: Path) -> Optional[Tuple[str, str]]:
    """Parse frontmatter ``name:`` and ``description:`` (folded forms too).

    Returns (name, description) or None when the frontmatter is unparseable.
    """
    raw = path.read_text(encoding="utf-8-sig")
    lines = re.split(r"\r?\n", raw)
    if len(lines) < 3 or lines[0].strip() != "---":
        return None

    end_idx = -1
    for i in range(1, len(lines)):
        if lines[i].strip() == "---":
            end_idx = i
            break
    if end_idx < 0:
        return None

    fm_lines = lines[1:end_idx]

    name: Optional[str] = None
    description: Optional[str] = None
    i = 0
    while i < len(fm_lines):
        line = fm_lines[i]
        m_name = re.match(r"^\s*name\s*:\s*(.+)$", line)
        m_desc = re.match(r"^\s*description\s*:\s*(.*)$", line)
        if m_name:
            name = m_name.group(1).strip().strip("'\"")
        elif m_desc:
            rest = m_desc.group(1).strip()
            if rest in (">-", ">", "|", "|-"):
                # folded scalar -- collect indented continuation
                buf: List[str] = []
                j = i + 1
                while j < len(fm_lines) and (
                        re.match(r"^\s+\S", fm_lines[j])
                        or fm_lines[j].strip() == ""):
                    if fm_lines[j].strip():
                        buf.append(fm_lines[j].strip())
                    j += 1
                description = " ".join(buf).strip()
                i = j - 1
            else:
                description = rest.strip().strip("'\"")
        i += 1

    if not name:
        return None
    return name, description or ""


def main(argv: Optional[List[str]] = None) -> int:
    parser = argparse.ArgumentParser(
        description="Generate SKILL_INDEX.md across all 5 IDE skill folders "
                    "from canonical .cursor/skills frontmatter.")
    parser.add_argument("-Apply", "--apply", dest="apply", action="store_true",
                        help="Write the SKILL_INDEX.md files (default: dry-run)")
    parser.add_argument("-RepoRoot", "--repo-root", dest="repo_root",
                        default=None,
                        help="Override the repo root (default: parent "
                             "directory of this script's folder)")
    args = parser.parse_args(argv)

    repo_root = Path(args.repo_root) if args.repo_root \
        else Path(__file__).resolve().parent.parent

    canonical_skills_dir = repo_root / ".cursor" / "skills"
    if not canonical_skills_dir.is_dir():
        print(f"ERROR: Could not locate .cursor/skills under '{repo_root}'.",
              file=sys.stderr)
        return 2

    targets = [repo_root / Path(t) for t in TARGET_DIRS]

    # Walk canonical skills folder
    entries: List[Tuple[str, str]] = []
    skill_dirs = sorted(
        (d for d in canonical_skills_dir.iterdir()
         if d.is_dir() and d.name.startswith("g-skl-")),
        key=lambda d: d.name)
    for skill_dir in skill_dirs:
        skill_file = skill_dir / "SKILL.md"
        if not skill_file.exists():
            continue
        fm = get_skill_frontmatter(skill_file)
        if fm is None:
            print(f"WARNING: Skipping '{skill_dir.name}' -- could not parse "
                  "frontmatter", file=sys.stderr)
            continue
        entries.append(fm)

    # Sort by name for stable output
    entries.sort(key=lambda e: e[0])

    index_lines = [f"- **{name}**: {desc}" for name, desc in entries]
    content = "\n".join(list(HEADER_LINES) + index_lines + [""])
    if not content.endswith("\n"):
        content += "\n"

    changed_targets: List[Path] = []
    unchanged_targets: List[Path] = []
    skipped_targets: List[Path] = []

    for target in targets:
        if not target.is_dir():
            skipped_targets.append(target)
            continue
        out_path = target / "SKILL_INDEX.md"
        existing = ""
        if out_path.exists():
            try:
                existing = out_path.read_text(encoding="utf-8-sig")
            except OSError:
                existing = ""
        if existing == content:
            unchanged_targets.append(out_path)
        else:
            changed_targets.append(out_path)
            if args.apply:
                # UTF-8 without BOM, LF newlines
                out_path.write_text(content, encoding="utf-8", newline="\n")

    print("")
    print("=== Skill Index Generator ===")
    print(f"Skills found        : {len(entries)}")
    print(f"Targets changed     : {len(changed_targets)}")
    print(f"Targets unchanged   : {len(unchanged_targets)}")
    print(f"Targets skipped     : {len(skipped_targets)}")
    if changed_targets:
        print("")
        print("Changed:")
        for p in changed_targets:
            print(f"  {p}")
    if skipped_targets:
        print("")
        print("Skipped (no skills folder):")
        for p in skipped_targets:
            print(f"  {p}")
    if not args.apply and changed_targets:
        print("")
        print("DRY RUN -- re-run with -Apply to write changes.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
